import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'pt-BR' | 'en-US' | 'es-ES';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pt-BR';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations: Record<Language, any> = {
  'pt-BR': {
    common: {
      home: 'Início',
      services: 'Serviços',
      blog: 'Blog',
      gallery: 'Galeria de Fotos',
      backToHome: 'Voltar ao início',
      findServices: 'Encontrar Serviços',
      registerService: 'Cadastrar Serviço',
      registerNow: 'Cadastre-se Agora',
      ourPartners: 'Nossos Parceiros',
      about: 'Sobre',
      partners: 'Parceiros',
      guides: 'Guias',
      destinations: 'Destinos',
      guidesRegistered: 'Guias Cadastrados',
      companies: 'Empresas',
      tourists: 'Turistas',
      suppliers: 'Fornecedores',
      activeAnglers: 'Pescadores Ativos',
      guideDirectory: 'Diretório de Guias',
      operationalDashboard: 'Dashboard Operacional',
      sponsorDashboard: 'Dashboard Patrocinadores',
      adminPanel: 'Painel Admin',
      bePartner: 'Seja um Parceiro',
      allRightsReserved: 'Todos os direitos reservados',
      booking: 'Reserva',
      weatherForecast: 'Previsão do Tempo',
      date: 'Data',
      time: 'Horário',
      guests: 'Convidados',
      status: 'Status',
      notes: 'Observações',
      cancel: 'Cancelar',
      loading: 'Carregando',
      noBookings: 'Nenhuma reserva encontrada',
      temperature: 'Temperatura',
      rain: 'Chuva',
      wind: 'Vento',
      humidity: 'Umidade',
      registerGuide: 'Cadastrar Guia de Pesca',
      registerCompany: 'Cadastrar Fornecedores',
      registering: 'Cadastrando...',
      signIn: 'Entrar',
      signUp: 'Cadastrar',
      welcome: 'Bem-vindo!',
      signInDescription: 'Entre ou crie sua conta para aproveitar todos os recursos',
      weatherPlanYourTrip: 'Planeje sua pescaria com a previsão do tempo para os próximos dias',
      trackStats: 'Acompanhe as estatísticas e métricas do sistema',
      lastMonthGrowth: 'no último mês',
      thisMonth: 'este mês',
      appVisits: 'Acessos ao Aplicativo',
      photoGallery: 'Galeria de Fotos',
      shareYourCatches: 'Compartilhe suas melhores pescarias com a comunidade',
      noCommunityPhotos: 'Nenhuma foto na galeria ainda. Seja o primeiro a compartilhar!',
      uploadPhotos: 'Fazer Upload de Fotos',
      changeLanguage: 'Alterar Idioma',
      notifications: 'Notificações',
      messages: 'Mensagens',
      loginOrRegister: 'Faça o Login ou Cadastre-se',
      name: 'Nome',
      email: 'Email',
      phone: 'Telefone',
      submit: 'Enviar',
      processing: 'Processando...',
      error: 'Erro',
      success: 'Sucesso!',
      redirecting: 'Redirecionando para pagamento',
      checkoutOpened: 'Uma nova aba foi aberta com o checkout do Mercado Pago.',
      errorProcessing: 'Erro ao processar',
      couldNotCreateSession: 'Não foi possível criar a sessão de pagamento.',
    },
    guides: { badge: 'Guias em Destaque', titleLine1: 'Os Melhores', titleLine2: 'Profissionais', viewAll: 'Ver Todos os Guias', viewProfile: 'Ver Perfil', specialty: 'Especialidade', },
    gallery: { badge: 'Galeria da Comunidade', titleLine1: 'Momentos', titleLine2: 'Inesquecíveis', subtitle: 'Compartilhe suas melhores pescarias e inspire outros pescadores', shareButton: 'Compartilhar Minha Pescaria', loginRequired: 'Login necessário', loginToShare: 'Faça login para compartilhar suas pescarias', },
    cta: { badge: 'Faça parte da comunidade', titleLine1: 'Pronto Para Sua', titleLine2: 'Maior Aventura?', subtitle: 'Junte-se a milhares de pescadores que já descobriram as melhores experiências de pesca do Brasil', beGuide: 'Seja um Guia', beGuideDesc: 'Cadastre-se e aumente sua clientela', beSupplier: 'Seja Fornecedor', beSupplierDesc: 'Divulgue seus produtos e serviços', bePartner: 'Seja Parceiro', bePartnerDesc: 'Patrocine e alcance milhares de pescadores', registerNow: 'Cadastrar Agora', beSponsor: 'Ser Patrocinador', },
    footer: { description: 'A maior plataforma de pesca do Brasil. Conectando pescadores, guias e fornecedores.', quickLinks: 'Links Rápidos', contact: 'Contato', findGuides: 'Encontrar Guias', beGuide: 'Seja um Guia', partners: 'Parceiros', about: 'Sobre Nós', rights: 'Todos os direitos reservados.', terms: 'Termos de Uso', privacy: 'Privacidade', },
    floatingCta: { mainButton: 'Sou Pescador', title: 'Se você é amante da natureza e adora uma boa pescaria, sua próxima aventura começa aqui!', subtitle: 'Acesse os melhores guias e destinos de pesca do Brasil. É grátis!', createAccount: 'Criar Minha Conta', hasAccount: 'Já tem conta?', login: 'Entrar', },
    features: { badge: 'Por que escolher o MasterFisher?', titleLine1: 'Tudo Para Sua', titleLine2: 'Pescaria', subtitle: 'A plataforma completa que conecta você a tudo que precisa para viver experiências inesquecíveis', findGuides: { title: 'Encontre Guias', desc: 'Guias especializados em diversas modalidades de pesca por todo o Brasil' }, suppliers: { title: 'Fornecedores', desc: 'Hotéis, pousadas, conveniências, postos de combustíveis, equipamentos, iscas e tudo que você precisa para sua pescaria' }, destinations: { title: 'Destinos', desc: 'Pantanal, Amazônia, Litoral e os melhores pontos de pesca' }, community: { title: 'Comunidade', desc: 'Compartilhe fotos, histórias e conecte-se com outros pescadores' }, groups: { title: 'Grupos de Pesca', desc: 'Encontre grupos e participe de expedições em equipe' }, ranking: { title: 'Ranking & Troféus', desc: 'Dispute rankings e mostre suas maiores capturas' }, explore: 'Explorar', },
    guideRegister: { title: 'Cadastro de Guia de Pesca',
      subtitle: 'Profissionalize seu serviço e conecte-se com milhares de pescadores',
      whyRegister: 'Por que se cadastrar como Guia?',
      whyRegisterDesc: 'MasterFisher é a plataforma líder que conecta guias profissionais com pescadores em busca de experiências autênticas',
      moreClients: 'Mais Clientes',
      moreClientsDesc: 'Alcance milhares de pescadores procurando guias profissionais',
      simplifiedManagement: 'Gestão Simplificada',
      simplifiedManagementDesc: 'Sistema completo de agendamentos e reservas',
      increaseIncome: 'Aumente sua Renda',
      increaseIncomeDesc: 'Expanda seu negócio com visibilidade profissional',
      credibility: 'Credibilidade',
      credibilityDesc: 'Perfil verificado e sistema de avaliações',
      experience: 'Experiência',
      specialties: 'Especialidades',
      registrationInfo: 'Informações para Cadastro',
      completeData: 'Complete os dados abaixo para iniciar seu cadastro como guia profissional',
      paymentValue: 'Investimento',
      oneTimePayment: 'Pagamento único',
      registrationFee: 'Taxa de cadastro',
      includesBenefits: 'Inclui todos os benefícios',
      fullName: 'Nome Completo',
      yearsExperience: 'Anos de Experiência',
      payAndFinalize: 'Pagar R$ 50,00 e Finalizar Cadastro',
      professionalPlanFeature1: 'Perfil profissional completo',
      professionalPlanFeature2: 'Sistema de agendamentos',
      professionalPlanFeature3: 'Galeria de fotos ilimitada',
      professionalPlanFeature4: 'Sistema de avaliações',
      professionalPlanFeature5: 'Visibilidade nacional',
      professionalPlanFeature6: 'Acesso vitalício',
      professionalPlanFeature7: 'Suporte técnico',
      professionalPlanFeature8: 'Ferramentas de marketing',
      completeAccessPlatform: 'Acesso completo e permanente à plataforma',
      professionalPlan: 'Plano Guia Profissional',
    },
    businessRegister: {
      title: 'Cadastro de Empresas',
      subtitle: 'Hotéis, Pousadas, Lojas e Fornecedores de Artigos de Pesca',
      expandBusiness: 'Expanda seu Negócio com MasterFisher',
      expandBusinessDesc: 'A plataforma perfeita para conectar sua empresa com pescadores apaixonados por todo o Brasil',
      nationalReach: 'Alcance Nacional',
      nationalReachDesc: 'Conecte-se com milhares de pescadores ativos',
      increaseSales: 'Aumente Vendas',
      increaseSalesDesc: 'Mais visibilidade, mais oportunidades de negócio',
      featuredLocation: 'Localização Destacada',
      featuredLocationDesc: 'Apareça nas buscas da sua região',
      credibility: 'Credibilidade',
      credibilityDesc: 'Sistema de avaliações e certificação',
      choosePlan: 'Escolha seu Plano',
      choosePlanDesc: 'Planos flexíveis para diferentes necessidades do seu negócio',
      monthlyPlan: 'Plano Mensal',
      annualPlan: 'Plano Anual',
      mostAdvantage: 'Mais Vantajoso',
      discount: '20% de desconto',
      allBenefitsMonthly: 'Todos os benefícios do plano mensal',
      annualSaving: '20% de economia no valor anual',
      premiumPosition: 'Posicionamento premium',
      searchHighlight: 'Destaque em buscas',
      annualPartnerBadge: 'Badge de parceiro anual',
      vipSupport: 'Suporte VIP 24/7',
      planSelected: 'Plano Selecionado',
      selectPlan: 'Selecionar Plano',
      registrationData: 'Dados do Cadastro',
      completeDataSubscribe: 'Complete seus dados para finalizar a assinatura do',
      companyName: 'Nome da Empresa',
      businessType: 'Tipo de Negócio',
      businessTypePlaceholder: 'Ex: Hotel, Pousada, Loja de Pesca',
      location: 'Localização',
      locationPlaceholder: 'Cidade/Estado',
      subscribe: 'Assinar',
      monthlyValue: 'Valor mensal',
      logoUploadTitle: 'Logotipo da Empresa',
      logoUploadDesc: 'Faça upload do seu logotipo para ser exibido na plataforma',
      logoUploadButton: 'Carregar Logotipo',
      logoUploadChange: 'Alterar Logotipo',
      logoUploadError: 'Erro no upload',
      logoUploadSuccess: 'Logotipo carregado com sucesso',
      logoRequirements: 'PNG, JPG ou SVG (Max. 2MB)',
      fullCompanyProfile: 'Perfil completo da empresa',
      productGallery: 'Galeria de produtos/serviços',
      reviewSystem: 'Sistema de avaliações',
      featuredVisibility: 'Visibilidade destacada',
      visitStats: 'Estatísticas de visitação',
      prioritySupport: 'Suporte prioritário',
    },
    findServices: {
      title: 'Encontre sua Próxima Aventura de Pesca',
      subtitle: 'Busque por guias, pousadas e tudo que você precisa para uma pescaria inesquecível.',
      whatLookingFor: 'O que você está procurando?',
      whereCityRegion: 'Onde? (Cidade ou região)',
      category: 'Categoria',
      all: 'Todos',
      fishingGuide: 'Guia de Pesca',
      hotel: 'Hotel',
      lodge: 'Pousada',
      fishingStore: 'Loja de Pesca',
      search: 'Buscar',
      advancedFilters: 'Filtros Avançados',
      refineSearch: 'Refine sua busca com filtros detalhados',
      minRating: 'Avaliação Mínima',
      allRatings: 'Todas',
      priceRange: 'Faixa de Preço (R$)',
      boatType: 'Tipo de Embarcación',
      speedboat: 'Lancha',
      aluminumBoat: 'Barco de Alumínio',
      woodenBoat: 'Barco de Madeira',
      equipmentIncluded: 'Equipamentos Inclusos',
      yes: 'Sim',
      no: 'Não',
      onlyPromotions: 'Apenas Promoções',
      clearFilters: 'Limpar Filtros',
      resultsFound: 'resultados encontrados',
      resultFound: 'resultado encontrado',
      promotion: 'Promoção',
      rating: 'avaliação',
      ratings: 'avaliações',
      viewDetails: 'Ver Detalhes',
      noResults: 'Nenhum resultado encontrado. Tente ajustar os filtros de busca.',
    },
    partnerCheckout: {
      title: 'Torne-se um Parceiro MasterFisher',
      subtitle: 'Conecte-se com milhares de pescadores e amplie seu negócio com visibilidade premium',
      solutionTitle: 'MasterFisher: A Solução Integrada',
      solutionDesc: 'MasterFisher é uma plataforma revolucionária que conecta os melhores guias de turismo de Pesca com turistas em busca de aventuras, transformando cada experiência em uma história inesquecível.',
      secureConnection: 'Conexão Segura',
      secureConnectionDesc: 'Liga guias certificados com turistas procurando experiências autênticas',
      intuitiveTools: 'Ferramentas Intuitivas',
      intuitiveToolsDesc: 'Interface amigável para reserva, avaliação e planificação de experiências',
      freePromotion: 'Promoção Grátis',
      freePromotionDesc: 'Visibilidade nacional e internacional para guias sem custos',
      monetization: 'Monetização por Publicidade',
      monetizationDesc: 'Modelo 100% gratuito para usuários, com lucro através de anúncios',
      quote: 'MasterFisher não é apenas uma plataforma, é uma experiência completa que transforma a pescaria em uma jornada inesquecível.',
      marketGrowthTitle: 'Um Mercado em Pleno Crescimento',
      globalMarket: 'Mercado Global',
      brazilianMarket: 'Mercado Brasileiro',
      whyPartner: 'Por que ser nosso parceiro?',
      whyPartnerDesc: 'A plataforma ideal para guias de pesca e fornecedores alcançarem mais clientes',
      forGuides: 'Para Guias de Pesca',
      forGuidesDesc: 'Divulgue seus serviços, gerencie agendamentos e aumente sua carteira de clientes com ferramentas profissionais',
      forSuppliers: 'Para Fornecedores',
      forSuppliersDesc: 'Mostre seus produtos e serviços para uma audiência engajada de pescadores apaixonados',
      choosePlan: 'Escolha seu Plano de Parceria',
      choosePlanDesc: 'Planos flexíveis para diferentes necessidades de negócio e níveis de visibilidade',
      mostPopular: 'Mais Popular',
      name: 'Nome',
      email: 'Email',
      phone: 'Telefone',
      company: 'Empresa',
      area: 'Área de Atuação',
      submit: 'Assinar Plano',
      planSelected: 'Plano Selecionado',
      selectPlan: 'Selecionar Plano',
      perMonth: '/mês',
      registrationInfo: 'Informações de Cadastro',
      completeData: 'Complete seus dados para finalizar a assinatura do plano',
      selectedPlanLabel: 'Plano Selecionado:',
      monthlyValue: 'Valor mensal',
      logoUploadTitle: 'Logotipo da Empresa',
      logoUploadDesc: 'Faça upload do seu logotipo para ser exibido na plataforma',
      logoUploadButton: 'Carregar Logotipo',
      logoUploadChange: 'Alterar Logotipo',
      logoUploadError: 'Erro no upload',
      logoUploadSuccess: 'Logotipo carregado com sucesso',
      logoRequirements: 'PNG, JPG ou SVG (Max. 2MB)',
      bronzeFeature1: 'Logotipo destacado no carrossel',
      bronzeFeature2: 'Acesso completo à plataforma',
      bronzeFeature3: 'Perfil básico',
      bronzeFeature4: 'Sistema de agendamentos',
      silverFeature1: 'Propaganda destacada',
      silverFeature2: '1 ponto de logotipo na plataforma',
      silverFeature3: 'Acesso completo à plataforma',
      silverFeature4: 'Perfil destacado',
      silverFeature5: 'Sistema de agendamentos avançado',
      silverFeature6: 'Suporte prioritário',
      goldFeature1: 'Propaganda com maior destaque',
      goldFeature2: 'Dois pontos de logotipos destacados',
      goldFeature3: 'Acesso completo à plataforma',
      goldFeature4: 'Perfil muito destacado',
      goldFeature5: 'Sistema de agendamentos premium',
      goldFeature6: 'Suporte VIP 24/7',
      goldFeature7: 'Analytics avançados',
      masterFeature1: 'Banner exclusivo rotativo no topo',
      masterFeature2: 'Logo 3x maior que parceiros regulares',
      masterFeature3: 'Seção "Parceiros Master" destacada',
      masterFeature4: 'Posicionamento fixo em todas as páginas',
      masterFeature5: 'Página institucional exclusiva',
      masterFeature6: 'Analytics avançados com geolocalização',
      masterFeature7: 'Co-branding em materiais promocionais',
      masterFeature8: 'Gerente de conta dedicado',
    },
    hero: { badge: 'A maior plataforma de pesca do Brasil', titleLine1: 'Sua Próxima', titleLine2: 'Grande Pescaria', titleLine3: 'Começa Aqui', subtitle: 'Conectamos você aos melhores guias de pesca, fornecedores e experiências inesquecíveis em todo o Brasil', },
    sponsors: { badge: 'Parceiros de Excelência', titleLine1: 'Nossos', titleLine2: 'Patrocinadores', subtitle: 'Marcas líderes que compartilham nossa paixão pela pesca e apoiam a conexão entre pescadores e os melhores guias do Brasil', meetBrand: 'Conheça a marca', partnerBrands: 'Marcas Parceiras', partnerBrandsDesc: 'As maiores marcas do mundo da pesca esportiva', becomePartnerTitle: 'Quer ser nosso parceiro?', becomePartnerDesc: 'Junte-se às maiores marcas do setor de pesca e alcance milhares de pescadores', becomePartnerBtn: 'Seja um Patrocinador', },
    about: { title: 'A Solução Integrada', whatIsTitle: 'O Que é MasterFisher?', whatIsDesc1: 'MasterFisher é uma plataforma revolucionária que conecta os melhores guias de turismo de Pesca com turistas em busca de aventuras, transformando cada experiência em uma história inesquecível.', whatIsDesc2: 'Desenvolvida como uma solução completa, a aplicação serve como uma verdadeira ponte entre os dois mundos, eliminando as barreiras para uma experiência de pescaria memorável.', completeSolution: 'solução completa', feature1Title: 'Conexão Segura', feature1Desc: 'Liga guias certificados com turistas procurando experiências autênticas.', feature2Title: 'Ferramentas Intuitivas', feature2Desc: 'Interface amigável para reserva, avaliação e planificação de experiências.', feature3Title: 'Promoção Grátis', feature3Desc: 'Visibilidade nacional e internacional para guias sem custos.', feature4Title: 'Monetização por Publicidade', feature4Desc: 'Modelo 100% gratuito para usuários, com lucro através de anúncios.', quote: 'MasterFisher não é apenas uma plataforma, é uma experiência completa que transforma a pescaria em uma jornada inesquecível.', readyTitle: 'Pronto para Começar?', readyDesc: 'Junte-se a milhares de pescadores e guias que já fazem parte da nossa comunidade.', registerFree: 'Cadastre-se Grátis', findGuides: 'Encontrar Guias', },
    
    partners: {
      title: 'Nossos Parceiros',
      subtitle: 'Empresas que acreditam e apoiam a pesca esportiva no Brasil',
      ctaTitle: 'Quer divulgar sua marca?',
      ctaDescription: 'Torne-se um parceiro patrocinador e alcance milhares de pescadores apaixonados',
      ctaButton: 'Seja um Parceiro Patrocinador',
      noSponsors: 'Nenhum patrocinador cadastrado ainda',
    },
    dashboard: {
      title: 'Dashboard Operacional',
      subtitle: 'Visão geral dos principais indicadores da plataforma MasterFisher.',
      registeredGuides: 'Guias Cadastrados',
      partnerCompanies: 'Empresas Parceiras',
      bookings: 'Agendamentos',
      activeAnglers: 'Pescadores Ativos',
      averageRating: 'Avaliação Média',
      guides: 'Guias',
      companies: 'Empresas',
      userGrowth: 'Crescimento de Usuários',
      userGrowthDesc: 'Novos pescadores cadastrados nos últimos 6 meses.',
      bookingsPerMonth: 'Agendamentos por Mês',
      bookingsPerMonthDesc: 'Total de pescarias agendadas nos últimos 6 meses.',
      recentActivities: 'Atividades Recentes',
      recentActivitiesDesc: 'Acompanhe as últimas ações na plataforma.',
      saveProjectState: 'Salvar Estado do Projeto',
    },
  },
  'en-US': {
    common: {
      home: 'Home',
      services: 'Services',
      blog: 'Blog',
      gallery: 'Photo Gallery',
      backToHome: 'Back to home',
      findServices: 'Find Services',
      registerService: 'Register Service',
      registerNow: 'Register Now',
      ourPartners: 'Our Partners',
      about: 'About',
      partners: 'Partners',
      guides: 'Guides',
      destinations: 'Destinations',
      guidesRegistered: 'Registered Guides',
      companies: 'Companies',
      tourists: 'Tourists',
      suppliers: 'Suppliers',
      activeAnglers: 'Active Anglers',
      guideDirectory: 'Guide Directory',
      operationalDashboard: 'Operational Dashboard',
      sponsorDashboard: 'Sponsor Dashboard',
      adminPanel: 'Admin Panel',
      bePartner: 'Become a Partner',
      allRightsReserved: 'All rights reserved',
      booking: 'Booking',
      weatherForecast: 'Weather Forecast',
      date: 'Date',
      time: 'Time',
      guests: 'Guests',
      status: 'Status',
      notes: 'Notes',
      cancel: 'Cancel',
      loading: 'Loading',
      noBookings: 'No bookings found',
      temperature: 'Temperature',
      rain: 'Rain',
      wind: 'Wind',
      humidity: 'Humidity',
      registerGuide: 'Register Fishing Guide',
      registerCompany: 'Register Suppliers',
      registering: 'Registering...',
      signIn: 'Sign In',
      signUp: 'Sign Up',
      welcome: 'Welcome!',
      signInDescription: 'Sign in or create your account to enjoy all features',
      weatherPlanYourTrip: 'Plan your fishing trip with the weather forecast for the next days',
      trackStats: 'Track system statistics and metrics',
      lastMonthGrowth: 'in the last month',
      thisMonth: 'this month',
      appVisits: 'App Visits',
      photoGallery: 'Photo Gallery',
      shareYourCatches: 'Share your best catches with the community',
      noCommunityPhotos: 'No photos in the gallery yet. Be the first to share!',
      uploadPhotos: 'Upload Photos',
      changeLanguage: 'Change Language',
      notifications: 'Notifications',
      messages: 'Messages',
      loginOrRegister: 'Sign In or Register',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      submit: 'Submit',
      processing: 'Processing...',
      error: 'Error',
      success: 'Success!',
      redirecting: 'Redirecting to payment',
      checkoutOpened: 'A new tab was opened with Mercado Pago checkout.',
      errorProcessing: 'Error processing',
      couldNotCreateSession: 'Could not create payment session.',
    },
    guides: { badge: 'Featured Guides', titleLine1: 'The Best', titleLine2: 'Professionals', viewAll: 'View All Guides', viewProfile: 'View Profile', specialty: 'Specialty', },
    gallery: { badge: 'Community Gallery', titleLine1: 'Unforgettable', titleLine2: 'Moments', subtitle: 'Share your best catches and inspire other anglers', shareButton: 'Share My Catch', loginRequired: 'Login Required', loginToShare: 'Log in to share your catches', },
    cta: { badge: 'Join the community', titleLine1: 'Ready For Your', titleLine2: 'Biggest Adventure?', subtitle: 'Join thousands of anglers who have discovered the best fishing experiences in Brazil', beGuide: 'Be a Guide', beGuideDesc: 'Register and grow your clientele', beSupplier: 'Be a Supplier', beSupplierDesc: 'Advertise your products and services', bePartner: 'Be a Partner', bePartnerDesc: 'Sponsor and reach thousands of anglers', registerNow: 'Register Now', beSponsor: 'Be a Sponsor', },
    footer: { description: 'The largest fishing platform in Brazil. Connecting anglers, guides and suppliers.', quickLinks: 'Quick Links', contact: 'Contact', findGuides: 'Find Guides', beGuide: 'Be a Guide', partners: 'Partners', about: 'About Us', rights: 'All rights reserved.', terms: 'Terms of Use', privacy: 'Privacy', },
    floatingCta: { mainButton: 'I am an Angler', title: 'If you love nature and a good fishing trip, your next adventure starts here!', subtitle: 'Access the best guides and fishing destinations in Brazil. It\'s free!', createAccount: 'Create My Account', hasAccount: 'Already have an account?', login: 'Sign In', },
    features: { badge: 'Why choose MasterFisher?', titleLine1: 'Everything For Your', titleLine2: 'Fishing Trip', subtitle: 'The complete platform connecting you to everything you need for unforgettable experiences', findGuides: { title: 'Find Guides', desc: 'Specialized guides in various fishing styles all over Brazil' }, suppliers: { title: 'Suppliers', desc: 'Hotels, lodges, convenience stores, gas stations, equipment, bait and everything you need for your fishing trip' }, destinations: { title: 'Destinations', desc: 'Pantanal, Amazon, Coast and the best fishing spots' }, community: { title: 'Community', desc: 'Share photos, stories and connect with other anglers' }, groups: { title: 'Fishing Groups', desc: 'Find groups and join team expeditions' }, ranking: { title: 'Ranking & Trophies', desc: 'Compete in rankings and show off your biggest catches' }, explore: 'Explore', },
    guideRegister: { title: 'Fishing Guide Registration',
      subtitle: 'Professionalize your service and connect with thousands of anglers',
      whyRegister: 'Why register as a Guide?',
      whyRegisterDesc: 'MasterFisher is the leading platform connecting professional guides with anglers seeking authentic experiences',
      moreClients: 'More Clients',
      moreClientsDesc: 'Reach thousands of anglers looking for professional guides',
      simplifiedManagement: 'Simplified Management',
      simplifiedManagementDesc: 'Complete booking and reservation system',
      increaseIncome: 'Increase Your Income',
      increaseIncomeDesc: 'Expand your business with professional visibility',
      credibility: 'Credibility',
      credibilityDesc: 'Verified profile and rating system',
      experience: 'Experience',
      specialties: 'Specialties',
      registrationInfo: 'Registration Information',
      completeData: 'Complete the information below to start your registration as a professional guide',
      paymentValue: 'Investment',
      oneTimePayment: 'One-time payment',
      registrationFee: 'Registration fee',
      includesBenefits: 'Includes all benefits',
      fullName: 'Full Name',
      yearsExperience: 'Years of Experience',
      payAndFinalize: 'Pay $50.00 and Complete Registration',
      professionalPlanFeature1: 'Complete professional profile',
      professionalPlanFeature2: 'Booking system',
      professionalPlanFeature3: 'Unlimited photo gallery',
      professionalPlanFeature4: 'Review system',
      professionalPlanFeature5: 'National visibility',
      professionalPlanFeature6: 'Lifetime access',
      professionalPlanFeature7: 'Technical support',
      professionalPlanFeature8: 'Marketing tools',
      completeAccessPlatform: 'Complete and permanent access to the platform',
      professionalPlan: 'Professional Guide Plan',
    },
    businessRegister: {
      title: 'Business Registration',
      subtitle: 'Hotels, Lodges, Stores and Fishing Supplies',
      expandBusiness: 'Expand Your Business with MasterFisher',
      expandBusinessDesc: 'The perfect platform to connect your company with passionate anglers throughout Brazil',
      nationalReach: 'National Reach',
      nationalReachDesc: 'Connect with thousands of active anglers',
      increaseSales: 'Increase Sales',
      increaseSalesDesc: 'More visibility, more business opportunities',
      featuredLocation: 'Featured Location',
      featuredLocationDesc: 'Appear in searches in your region',
      credibility: 'Credibility',
      credibilityDesc: 'Rating and certification system',
      choosePlan: 'Choose Your Plan',
      choosePlanDesc: 'Flexible plans for different business needs',
      monthlyPlan: 'Monthly Plan',
      annualPlan: 'Annual Plan',
      mostAdvantage: 'Best Value',
      discount: '20% discount',
      allBenefitsMonthly: 'All monthly plan benefits',
      annualSaving: '20% savings on annual value',
      premiumPosition: 'Premium positioning',
      searchHighlight: 'Search highlighting',
      annualPartnerBadge: 'Annual partner badge',
      vipSupport: 'VIP 24/7 support',
      planSelected: 'Selected Plan',
      selectPlan: 'Select Plan',
      registrationData: 'Registration Data',
      completeDataSubscribe: 'Complete your details to finalize the subscription for',
      companyName: 'Company Name',
      businessType: 'Business Type',
      businessTypePlaceholder: 'Ex: Hotel, Lodge, Fishing Store',
      location: 'Location',
      locationPlaceholder: 'City/State',
      subscribe: 'Subscribe',
      monthlyValue: 'Monthly value',
      logoUploadTitle: 'Company Logo',
      logoUploadDesc: 'Upload your logo to be displayed on the platform',
      logoUploadButton: 'Upload Logo',
      logoUploadChange: 'Change Logo',
      logoUploadError: 'Upload error',
      logoUploadSuccess: 'Logo uploaded successfully',
      logoRequirements: 'PNG, JPG or SVG (Max. 2MB)',
      fullCompanyProfile: 'Complete company profile',
      productGallery: 'Product/service gallery',
      reviewSystem: 'Review system',
      featuredVisibility: 'Featured visibility',
      visitStats: 'Visit statistics',
      prioritySupport: 'Priority support',
    },
    findServices: {
      title: 'Find Your Next Fishing Adventure',
      subtitle: 'Search for guides, lodges and everything you need for an unforgettable fishing trip.',
      whatLookingFor: 'What are you looking for?',
      whereCityRegion: 'Where? (City or region)',
      category: 'Category',
      all: 'All',
      fishingGuide: 'Fishing Guide',
      hotel: 'Hotel',
      lodge: 'Lodge',
      fishingStore: 'Fishing Store',
      search: 'Search',
      advancedFilters: 'Advanced Filters',
      refineSearch: 'Refine your search with detailed filters',
      minRating: 'Minimum Rating',
      allRatings: 'All',
      priceRange: 'Price Range ($)',
      boatType: 'Boat Type',
      speedboat: 'Speedboat',
      aluminumBoat: 'Aluminum Boat',
      woodenBoat: 'Wooden Boat',
      equipmentIncluded: 'Equipment Included',
      yes: 'Yes',
      no: 'No',
      onlyPromotions: 'Promotions Only',
      clearFilters: 'Clear Filters',
      resultsFound: 'results found',
      resultFound: 'result found',
      promotion: 'Promotion',
      rating: 'rating',
      ratings: 'ratings',
      viewDetails: 'View Details',
      noResults: 'No results found. Try adjusting the search filters.',
    },
    partnerCheckout: {
      title: 'Become a MasterFisher Partner',
      subtitle: 'Connect with thousands of anglers and grow your business with premium visibility',
      solutionTitle: 'MasterFisher: The Integrated Solution',
      solutionDesc: 'MasterFisher is a revolutionary platform that connects the best fishing tour guides with tourists seeking adventures, transforming every experience into an unforgettable story.',
      secureConnection: 'Secure Connection',
      secureConnectionDesc: 'Links certified guides with tourists looking for authentic experiences',
      intuitiveTools: 'Intuitive Tools',
      intuitiveToolsDesc: 'User-friendly interface for booking, rating and planning experiences',
      freePromotion: 'Free Promotion',
      freePromotionDesc: 'National and international visibility for guides at no cost',
      monetization: 'Monetization through Advertising',
      monetizationDesc: '100% free model for users, with profit through ads',
      quote: 'MasterFisher is not just a platform, it is a complete experience that transforms fishing into an unforgettable journey.',
      marketGrowthTitle: 'A Market in Full Growth',
      globalMarket: 'Global Market',
      brazilianMarket: 'Brazilian Market',
      whyPartner: 'Why become our partner?',
      whyPartnerDesc: 'The ideal platform for fishing guides and suppliers to reach more customers',
      forGuides: 'For Fishing Guides',
      forGuidesDesc: 'Promote your services, manage bookings and grow your client base with professional tools',
      forSuppliers: 'For Suppliers',
      forSuppliersDesc: 'Showcase your products and services to an engaged audience of passionate anglers',
      choosePlan: 'Choose Your Partnership Plan',
      choosePlanDesc: 'Flexible plans for different business needs and visibility levels',
      mostPopular: 'Most Popular',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      company: 'Company',
      area: 'Business Area',
      submit: 'Subscribe Plan',
      planSelected: 'Selected Plan',
      selectPlan: 'Select Plan',
      perMonth: '/month',
      registrationInfo: 'Registration Information',
      completeData: 'Complete your details to finalize the subscription for the plan',
      selectedPlanLabel: 'Selected Plan:',
      monthlyValue: 'Monthly value',
      logoUploadTitle: 'Company Logo',
      logoUploadDesc: 'Upload your logo to be displayed on the platform',
      logoUploadButton: 'Upload Logo',
      logoUploadChange: 'Change Logo',
      logoUploadError: 'Upload error',
      logoUploadSuccess: 'Logo uploaded successfully',
      logoRequirements: 'PNG, JPG or SVG (Max. 2MB)',
      bronzeFeature1: 'Featured logo in carousel',
      bronzeFeature2: 'Full platform access',
      bronzeFeature3: 'Basic profile',
      bronzeFeature4: 'Booking system',
      silverFeature1: 'Featured advertising',
      silverFeature2: '1 logo spot on platform',
      silverFeature3: 'Full platform access',
      silverFeature4: 'Featured profile',
      silverFeature5: 'Advanced booking system',
      silverFeature6: 'Priority support',
      goldFeature1: 'Top featured advertising',
      goldFeature2: 'Two featured logo spots',
      goldFeature3: 'Full platform access',
      goldFeature4: 'Highly featured profile',
      goldFeature5: 'Premium booking system',
      goldFeature6: 'VIP 24/7 support',
      goldFeature7: 'Advanced analytics',
      masterFeature1: 'Exclusive rotating banner at top',
      masterFeature2: 'Logo 3x larger than regular partners',
      masterFeature3: '"Master Partners" featured section',
      masterFeature4: 'Fixed positioning on all pages',
      masterFeature5: 'Exclusive institutional page',
      masterFeature6: 'Advanced analytics with geolocation',
      masterFeature7: 'Co-branding in promotional materials',
      masterFeature8: 'Dedicated account manager',
    },
    hero: { badge: 'The largest fishing platform in Brazil', titleLine1: 'Your Next', titleLine2: 'Great Fishing Trip', titleLine3: 'Starts Here', subtitle: 'We connect you to the best fishing guides, suppliers and unforgettable experiences throughout Brazil', },
    sponsors: { badge: 'Excellence Partners', titleLine1: 'Our', titleLine2: 'Sponsors', subtitle: 'Leading brands that share our passion for fishing and support the connection between anglers and the best guides in Brazil', meetBrand: 'Meet the brand', partnerBrands: 'Partner Brands', partnerBrandsDesc: 'The biggest brands in the sport fishing world', becomePartnerTitle: 'Want to be our partner?', becomePartnerDesc: 'Join the biggest brands in the fishing industry and reach thousands of anglers', becomePartnerBtn: 'Become a Sponsor', },
    about: { title: 'The Integrated Solution', whatIsTitle: 'What is MasterFisher?', whatIsDesc1: 'MasterFisher is a revolutionary platform that connects the best fishing tourism guides with tourists in search of adventure, transforming every experience into an unforgettable story.', whatIsDesc2: 'Developed as a complete solution, the application serves as a true bridge between the two worlds, eliminating barriers to a memorable fishing experience.', completeSolution: 'complete solution', feature1Title: 'Secure Connection', feature1Desc: 'Connects certified guides with tourists looking for authentic experiences.', feature2Title: 'Intuitive Tools', feature2Desc: 'User-friendly interface for booking, reviewing, and planning experiences.', feature3Title: 'Free Promotion', feature3Desc: 'National and international visibility for guides at no cost.', feature4Title: 'Ad Monetization', feature4Desc: '100% free model for users, with profit through advertisements.', quote: 'MasterFisher is not just a platform, it is a complete experience that transforms fishing into an unforgettable journey.', readyTitle: 'Ready to Start?', readyDesc: 'Join thousands of anglers and guides who are already part of our community.', registerFree: 'Sign Up Free', findGuides: 'Find Guides', },
    partners: {
      title: 'Our Partners',
      subtitle: 'Companies that believe in and support sport fishing in Brazil',
      ctaTitle: 'Want to promote your brand?',
      ctaDescription: 'Become a sponsor partner and reach thousands of passionate anglers',
      ctaButton: 'Become a Sponsor Partner',
      noSponsors: 'No sponsors registered yet',
    },
    dashboard: {
      title: 'Operational Dashboard',
      subtitle: 'Overview of MasterFisher platform key indicators.',
      registeredGuides: 'Registered Guides',
      partnerCompanies: 'Partner Companies',
      bookings: 'Bookings',
      activeAnglers: 'Active Anglers',
      averageRating: 'Average Rating',
      guides: 'Guides',
      companies: 'Companies',
      userGrowth: 'User Growth',
      userGrowthDesc: 'New registered anglers in the last 6 months.',
      bookingsPerMonth: 'Bookings per Month',
      bookingsPerMonthDesc: 'Total fishing trips scheduled in the last 6 months.',
      recentActivities: 'Recent Activities',
      recentActivitiesDesc: 'Track the latest actions on the platform.',
      saveProjectState: 'Save Project State',
    },
  },
  'es-ES': {
    common: {
      home: 'Inicio',
      services: 'Servicios',
      blog: 'Blog',
      gallery: 'Galería de Fotos',
      backToHome: 'Volver al inicio',
      findServices: 'Encontrar Servicios',
      registerService: 'Registrar Servicio',
      registerNow: 'Regístrate Ahora',
      ourPartners: 'Nuestros Socios',
      about: 'Acerca de',
      partners: 'Socios',
      guides: 'Guías',
      destinations: 'Destinos',
      guidesRegistered: 'Guías Registrados',
      companies: 'Empresas',
      tourists: 'Turistas',
      suppliers: 'Proveedores',
      activeAnglers: 'Pescadores Activos',
      guideDirectory: 'Directorio de Guías',
      operationalDashboard: 'Panel Operacional',
      sponsorDashboard: 'Panel de Patrocinadores',
      adminPanel: 'Panel de Administración',
      bePartner: 'Sé un Socio',
      allRightsReserved: 'Todos los derechos reservados',
      booking: 'Reserva',
      weatherForecast: 'Pronóstico del Tiempo',
      date: 'Fecha',
      time: 'Hora',
      guests: 'Invitados',
      status: 'Estado',
      notes: 'Notas',
      cancel: 'Cancelar',
      loading: 'Cargando',
      noBookings: 'No se encontraron reservas',
      temperature: 'Temperatura',
      rain: 'Lluvia',
      wind: 'Viento',
      humidity: 'Humedad',
      registerGuide: 'Registrar Guía de Pesca',
      registerCompany: 'Registrar Proveedores',
      registering: 'Registrando...',
      signIn: 'Ingresar',
      signUp: 'Registrarse',
      welcome: '¡Bienvenido!',
      signInDescription: 'Ingresa o crea tu cuenta para disfrutar de todas las funciones',
      weatherPlanYourTrip: 'Planifica tu pesca con el pronóstico del tiempo para los próximos días',
      trackStats: 'Realiza seguimiento de estadísticas y métricas del sistema',
      lastMonthGrowth: 'en el último mes',
      thisMonth: 'este mes',
      appVisits: 'Visitas a la App',
      photoGallery: 'Galería de Fotos',
      shareYourCatches: 'Comparte tus mejores capturas con la comunidad',
      noCommunityPhotos: '¡Aún no hay fotos en la galería. Sé el primero en compartir!',
      uploadPhotos: 'Subir Fotos',
      changeLanguage: 'Cambiar Idioma',
      notifications: 'Notificaciones',
      messages: 'Mensajes',
      loginOrRegister: 'Inicia Sesión o Regístrate',
      name: 'Nombre',
      email: 'Email',
      phone: 'Teléfono',
      submit: 'Enviar',
      processing: 'Procesando...',
      error: 'Error',
      success: '¡Éxito!',
      redirecting: 'Redirigiendo al pago',
      checkoutOpened: 'Se abrió una nueva pestaña con el checkout de Mercado Pago.',
      errorProcessing: 'Error al procesar',
      couldNotCreateSession: 'No se pudo crear la sesión de pago.',
    },
    guides: { badge: 'Guías Destacados', titleLine1: 'Los Mejores', titleLine2: 'Profesionales', viewAll: 'Ver Todos los Guías', viewProfile: 'Ver Perfil', specialty: 'Especialidad', },
    gallery: { badge: 'Galería de la Comunidad', titleLine1: 'Momentos', titleLine2: 'Inolvidables', subtitle: 'Comparte tus mejores capturas e inspira a otros pescadores', shareButton: 'Compartir Mi Pesca', loginRequired: 'Inicio de sesión necesario', loginToShare: 'Inicia sesión para compartir tus capturas', },
    cta: { badge: 'Únete a la comunidad', titleLine1: '¿Listo Para Tu', titleLine2: 'Mayor Aventura?', subtitle: 'Únete a miles de pescadores que ya han descubierto las mejores experiencias de pesca en Brasil', beGuide: 'Sé un Guía', beGuideDesc: 'Regístrate y aumenta tu clientela', beSupplier: 'Sé Proveedor', beSupplierDesc: 'Publicita tus productos y servicios', bePartner: 'Sé Socio', bePartnerDesc: 'Patrocina y llega a miles de pescadores', registerNow: 'Registrarse Ahora', beSponsor: 'Ser Patrocinador', },
    footer: { description: 'La mayor plataforma de pesca de Brasil. Conectando pescadores, guías y proveedores.', quickLinks: 'Enlaces Rápidos', contact: 'Contacto', findGuides: 'Encontrar Guías', beGuide: 'Sé un Guía', partners: 'Socios', about: 'Sobre Nosotros', rights: 'Todos los derechos reservados.', terms: 'Términos de Uso', privacy: 'Privacidad', },
    floatingCta: { mainButton: 'Soy Pescador', title: 'Si eres amante de la naturaleza y te encanta una buena pesca, ¡tu próxima aventura comienza aquí!', subtitle: 'Accede a los mejores guías y destinos de pesca de Brasil. ¡Es gratis!', createAccount: 'Crear Mi Cuenta', hasAccount: '¿Ya tienes cuenta?', login: 'Entrar', },
    features: { badge: '¿Por qué elegir MasterFisher?', titleLine1: 'Todo Para Tu', titleLine2: 'Pesca', subtitle: 'La plataforma completa que te conecta con todo lo que necesitas para vivir experiencias inolvidables', findGuides: { title: 'Encontrar Guías', desc: 'Guías especializados en diversas modalidades de pesca por todo Brasil' }, suppliers: { title: 'Proveedores', desc: 'Hoteles, posadas, tiendas, gasolineras, equipos, cebos y todo lo que necesitas para tu pesca' }, destinations: { title: 'Destinos', desc: 'Pantanal, Amazonia, Litoral y los mejores puntos de pesca' }, community: { title: 'Comunidad', desc: 'Comparte fotos, historias y conéctate con otros pescadores' }, groups: { title: 'Grupos de Pesca', desc: 'Encuentra grupos y participa en expediciones en equipo' }, ranking: { title: 'Ranking y Trofeos', desc: 'Compite en rankings y muestra tus mayores capturas' }, explore: 'Explorar', },
    guideRegister: { title: 'Registro de Guía de Pesca',
      subtitle: 'Profesionaliza tu servicio y conéctate con miles de pescadores',
      whyRegister: '¿Por qué registrarse como Guía?',
      whyRegisterDesc: 'MasterFisher es la plataforma líder que conecta guías profesionales con pescadores en busca de experiencias auténticas',
      moreClients: 'Más Clientes',
      moreClientsDesc: 'Alcanza miles de pescadores buscando guías profesionales',
      simplifiedManagement: 'Gestión Simplificada',
      simplifiedManagementDesc: 'Sistema completo de reservas y agendamiento',
      increaseIncome: 'Aumenta tus Ingresos',
      increaseIncomeDesc: 'Expande tu negocio con visibilidad profesional',
      credibility: 'Credibilidad',
      credibilityDesc: 'Perfil verificado y sistema de evaluaciones',
      experience: 'Experiencia',
      specialties: 'Especialidades',
      registrationInfo: 'Información de Registro',
      completeData: 'Completa la información a continuación para iniciar tu registro como guía profesional',
      paymentValue: 'Inversión',
      oneTimePayment: 'Pago único',
      registrationFee: 'Tarifa de registro',
      includesBenefits: 'Incluye todos los beneficios',
      fullName: 'Nombre Completo',
      yearsExperience: 'Años de Experiencia',
      payAndFinalize: 'Pagar R$ 50,00 y Finalizar Registro',
      professionalPlanFeature1: 'Perfil profesional completo',
      professionalPlanFeature2: 'Sistema de reservas',
      professionalPlanFeature3: 'Galería de fotos ilimitada',
      professionalPlanFeature4: 'Sistema de evaluaciones',
      professionalPlanFeature5: 'Visibilidad nacional',
      professionalPlanFeature6: 'Acceso vitalicio',
      professionalPlanFeature7: 'Soporte técnico',
      professionalPlanFeature8: 'Herramientas de marketing',
      completeAccessPlatform: 'Acceso completo y permanente a la plataforma',
      professionalPlan: 'Plan Guía Profesional',
    },
    businessRegister: {
      title: 'Registro de Empresas',
      subtitle: 'Hoteles, Posadas, Tiendas y Proveedores de Artículos de Pesca',
      expandBusiness: 'Expanda su Negocio con MasterFisher',
      expandBusinessDesc: 'La plataforma perfecta para conectar su empresa con pescadores apasionados de todo Brasil',
      nationalReach: 'Alcance Nacional',
      nationalReachDesc: 'Conéctese con miles de pescadores activos',
      increaseSales: 'Aumente las Ventas',
      increaseSalesDesc: 'Más visibilidad, más oportunidades de negocio',
      featuredLocation: 'Ubicación Destacada',
      featuredLocationDesc: 'Aparezca en las búsquedas de su región',
      credibility: 'Credibilidad',
      credibilityDesc: 'Sistema de evaluaciones y certificación',
      choosePlan: 'Elija su Plan',
      choosePlanDesc: 'Planes flexibles para diferentes necesidades empresariales',
      monthlyPlan: 'Plan Mensual',
      annualPlan: 'Plan Anual',
      mostAdvantage: 'Más Ventajoso',
      discount: '20% de descuento',
      allBenefitsMonthly: 'Todos los beneficios del plan mensual',
      annualSaving: '20% de ahorro en el valor anual',
      premiumPosition: 'Posicionamiento premium',
      searchHighlight: 'Destaque en búsquedas',
      annualPartnerBadge: 'Insignia de socio anual',
      vipSupport: 'Soporte VIP 24/7',
      planSelected: 'Plan Seleccionado',
      selectPlan: 'Seleccionar Plan',
      registrationData: 'Datos de Registro',
      completeDataSubscribe: 'Complete sus datos para finalizar la suscripción del',
      companyName: 'Nombre de la Empresa',
      businessType: 'Tipo de Negocio',
      businessTypePlaceholder: 'Ej: Hotel, Posada, Tienda de Pesca',
      location: 'Ubicación',
      locationPlaceholder: 'Ciudad/Estado',
      subscribe: 'Suscribirse',
      monthlyValue: 'Valor mensual',
      logoUploadTitle: 'Logotipo de la Empresa',
      logoUploadDesc: 'Sube tu logotipo para que aparezca en la plataforma',
      logoUploadButton: 'Cargar Logotipo',
      logoUploadChange: 'Cambiar Logotipo',
      logoUploadError: 'Error de carga',
      logoUploadSuccess: 'Logotipo cargado con éxito',
      logoRequirements: 'PNG, JPG o SVG (Max. 2MB)',
      fullCompanyProfile: 'Perfil completo de la empresa',
      productGallery: 'Galería de productos/servicios',
      reviewSystem: 'Sistema de evaluaciones',
      featuredVisibility: 'Visibilidad destacada',
      visitStats: 'Estadísticas de visitas',
      prioritySupport: 'Soporte prioritario',
    },
    findServices: {
      title: 'Encuentre su Próxima Aventura de Pesca',
      subtitle: 'Busque guías, posadas y todo lo que necesita para una pesca inolvidable.',
      whatLookingFor: '¿Qué está buscando?',
      whereCityRegion: '¿Dónde? (Ciudad o región)',
      category: 'Categoría',
      all: 'Todos',
      fishingGuide: 'Guía de Pesca',
      hotel: 'Hotel',
      lodge: 'Posada',
      fishingStore: 'Tienda de Pesca',
      search: 'Buscar',
      advancedFilters: 'Filtros Avanzados',
      refineSearch: 'Refine su búsqueda con filtros detallados',
      minRating: 'Calificación Mínima',
      allRatings: 'Todas',
      priceRange: 'Rango de Precio (R$)',
      boatType: 'Tipo de Embarcación',
      speedboat: 'Lancha',
      aluminumBoat: 'Barco de Aluminio',
      woodenBoat: 'Barco de Madera',
      equipmentIncluded: 'Equipos Incluidos',
      yes: 'Sí',
      no: 'No',
      onlyPromotions: 'Solo Promociones',
      clearFilters: 'Limpiar Filtros',
      resultsFound: 'resultados encontrados',
      resultFound: 'resultado encontrado',
      promotion: 'Promoción',
      rating: 'evaluación',
      ratings: 'evaluaciones',
      viewDetails: 'Ver Detalles',
      noResults: 'No se encontraron resultados. Intente ajustar los filtros de búsqueda.',
    },
    partnerCheckout: {
      title: 'Conviértete en Socio de MasterFisher',
      subtitle: 'Conéctate con miles de pescadores y amplía tu negocio con visibilidad premium',
      solutionTitle: 'MasterFisher: La Solución Integrada',
      solutionDesc: 'MasterFisher es una plataforma revolucionaria que conecta a los mejores guías de turismo de pesca con turistas en busca de aventuras, transformando cada experiencia en una historia inolvidable.',
      secureConnection: 'Conexión Segura',
      secureConnectionDesc: 'Conecta guías certificados con turistas buscando experiencias auténticas',
      intuitiveTools: 'Herramientas Intuitivas',
      intuitiveToolsDesc: 'Interfaz amigable para reservas, evaluaciones y planificación de experiencias',
      freePromotion: 'Promoción Gratuita',
      freePromotionDesc: 'Visibilidad nacional e internacional para guías sin costos',
      monetization: 'Monetización por Publicidad',
      monetizationDesc: 'Modelo 100% gratuito para usuarios, con beneficios a través de anuncios',
      quote: 'MasterFisher no es solo una plataforma, es una experiencia completa que transforma la pesca en un viaje inolvidable.',
      marketGrowthTitle: 'Un Mercado en Pleno Crecimiento',
      globalMarket: 'Mercado Global',
      brazilianMarket: 'Mercado Brasileño',
      whyPartner: '¿Por qué ser nuestro socio?',
      whyPartnerDesc: 'La plataforma ideal para guías de pesca y proveedores para alcanzar más clientes',
      forGuides: 'Para Guías de Pesca',
      forGuidesDesc: 'Promociona tus servicios, gestiona reservas y aumenta tu cartera de clientes con herramientas profesionales',
      forSuppliers: 'Para Proveedores',
      forSuppliersDesc: 'Muestra tus productos y servicios a una audiencia comprometida de pescadores apasionados',
      choosePlan: 'Elige tu Plan de Asociación',
      choosePlanDesc: 'Planes flexibles para diferentes necesidades de negocio y niveles de visibilidad',
      mostPopular: 'Más Popular',
      name: 'Nombre',
      email: 'Email',
      phone: 'Teléfono',
      company: 'Empresa',
      area: 'Área de Actuación',
      submit: 'Suscribir Plan',
      planSelected: 'Plan Seleccionado',
      selectPlan: 'Seleccionar Plan',
      perMonth: '/mes',
      registrationInfo: 'Información de Registro',
      completeData: 'Complete sus datos para finalizar la suscripción del plan',
      selectedPlanLabel: 'Plan Selecionado:',
      monthlyValue: 'Valor mensual',
      logoUploadTitle: 'Logotipo de la Empresa',
      logoUploadDesc: 'Sube tu logotipo para que aparezca en la plataforma',
      logoUploadButton: 'Cargar Logotipo',
      logoUploadChange: 'Cambiar Logotipo',
      logoUploadError: 'Error de carga',
      logoUploadSuccess: 'Logotipo cargado con éxito',
      logoRequirements: 'PNG, JPG o SVG (Max. 2MB)',
      bronzeFeature1: 'Logotipo destacado en carrusel',
      bronzeFeature2: 'Acceso completo a la plataforma',
      bronzeFeature3: 'Perfil básico',
      bronzeFeature4: 'Sistema de reservas',
      silverFeature1: 'Publicidad destacada',
      silverFeature2: '1 punto de logotipo en plataforma',
      silverFeature3: 'Acceso completo a la plataforma',
      silverFeature4: 'Perfil destacado',
      silverFeature5: 'Sistema de reservas avanzado',
      silverFeature6: 'Soporte prioritario',
      goldFeature1: 'Publicidad con mayor destaque',
      goldFeature2: 'Dos puntos de logotipos destacados',
      goldFeature3: 'Acceso completo a la plataforma',
      goldFeature4: 'Perfil muy destacado',
      goldFeature5: 'Sistema de reservas premium',
      goldFeature6: 'Soporte VIP 24/7',
      goldFeature7: 'Analytics avanzados',
      masterFeature1: 'Banner exclusivo rotativo en la parte superior',
      masterFeature2: 'Logo 3x más grande que socios regulares',
      masterFeature3: 'Sección "Socios Master" destacada',
      masterFeature4: 'Posicionamiento fijo en todas las páginas',
      masterFeature5: 'Página institucional exclusiva',
      masterFeature6: 'Analytics avanzados con geolocalización',
      masterFeature7: 'Co-branding en materiales promocionales',
      masterFeature8: 'Gerente de cuenta dedicado',
    },
    hero: { badge: 'La mayor plataforma de pesca de Brasil', titleLine1: 'Tu Próxima', titleLine2: 'Gran Pesca', titleLine3: 'Comienza Aquí', subtitle: 'Te conectamos con los mejores guías de pesca, proveedores y experiencias inolvidables en todo Brasil', },
    sponsors: { badge: 'Socios de Excelencia', titleLine1: 'Nuestros', titleLine2: 'Patrocinadores', subtitle: 'Marcas líderes que comparten nuestra pasión por la pesca y apoyan la conexión entre pescadores y los mejores guías de Brasil', meetBrand: 'Conoce la marca', partnerBrands: 'Marcas Asociadas', partnerBrandsDesc: 'Las mayores marcas del mundo de la pesca deportiva', becomePartnerTitle: '¿Quieres ser nuestro socio?', becomePartnerDesc: 'Únete a las mayores marcas del sector pesquero y llega a miles de pescadores', becomePartnerBtn: 'Ser Patrocinador', },
    about: { title: 'La Solución Integrada', whatIsTitle: '¿Qué es MasterFisher?', whatIsDesc1: 'MasterFisher es una plataforma revolucionaria que conecta a los mejores guías de turismo de pesca con turistas en busca de aventuras, transformando cada experiencia en una historia inolvidable.', whatIsDesc2: 'Desarrollada como una solución completa, la aplicación sirve como un verdadero puente entre los dos mundos, eliminando las barreras para una experiencia de pesca memorable.', completeSolution: 'solución completa', feature1Title: 'Conexión Segura', feature1Desc: 'Conecta guías certificados con turistas que buscan experiencias auténticas.', feature2Title: 'Herramientas Intuitivas', feature2Desc: 'Interfaz amigable para reserva, evaluación y planificación de experiencias.', feature3Title: 'Promoción Gratis', feature3Desc: 'Visibilidad nacional e internacional para guías sin costo.', feature4Title: 'Monetización por Publicidad', feature4Desc: 'Modelo 100% gratuito para usuarios, con ganancias a través de anuncios.', quote: 'MasterFisher no es solo una plataforma, es una experiencia completa que transforma la pesca en un viaje inolvidable.', readyTitle: '¿Listo para Empezar?', readyDesc: 'Únete a miles de pescadores y guías que ya forman parte de nuestra comunidad.', registerFree: 'Regístrate Gratis', findGuides: 'Encontrar Guías', },
    partners: {
      title: 'Nuestros Socios',
      subtitle: 'Empresas que creen y apoyan la pesca deportiva en Brasil',
      ctaTitle: '¿Quieres divulgar tu marca?',
      ctaDescription: 'Conviértete en socio patrocinador y alcanza a miles de pescadores apasionados',
      ctaButton: 'Ser un Socio Patrocinador',
      noSponsors: 'Aún no hay patrocinadores registrados',
    },
    dashboard: {
      title: 'Panel Operacional',
      subtitle: 'Visión general de los principales indicadores de la plataforma MasterFisher.',
      registeredGuides: 'Guías Registrados',
      partnerCompanies: 'Empresas Asociadas',
      bookings: 'Reservas',
      activeAnglers: 'Pescadores Activos',
      averageRating: 'Calificación Promedio',
      guides: 'Guías',
      companies: 'Empresas',
      userGrowth: 'Crecimiento de Usuarios',
      userGrowthDesc: 'Nuevos pescadores registrados en los últimos 6 meses.',
      bookingsPerMonth: 'Reservas por Mes',
      bookingsPerMonthDesc: 'Total de viajes de pesca programados en los últimos 6 meses.',
      recentActivities: 'Actividades Recientes',
      recentActivitiesDesc: 'Sigue las últimas acciones en la plataforma.',
      saveProjectState: 'Guardar Estado del Proyecto',
    },
  },
};
